version: "3.7"

services:
  database:
    image: mysql:5.7
    environment:
      MYSQL_USER: sample
      MYSQL_DATABASE: feed
      MYSQL_PASSWORD: 12345678
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - "./database/feed/:/var/lib/mysql"
    ports:
      - "3306:3306"
    container_name: feed
    networks:
      - backend-network

  spring-boot:
    build:
      context: ./plee-auth
      dockerfile: Dockerfile
    image: plee_auth
    ports:
      - "8080:8080"
    container_name: plee_auth
    restart: always
    depends_on:
      - database
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://plee_mysql:3306/feed?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
      SPRING_DATASOURCE_USERNAME: sample
      SPRING_DATASOURCE_PASSWORD: 12345678