spring:
  datasource:
    url: jdbc:mysql://localhost:3306/new_park?sueSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    password: 12345678
    username: sample
  jpa:
    properties:
      hibernate:
        format_sql: true

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type : trace

